name: Clone luci-app-tinyfilemanager

on:
  push:
    branches:
      - main

jobs:
  clone_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v3

    - name: Clone luci-app-tinyfilemanager
      run: |
        git clone --depth=1 https://github.com/muink/luci-app-tinyfilemanager.git luci-app-tinyfm

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add luci-app-tinyfm
        git commit -m "Add luci-app-tinyfilemanager as luci-app-tinyfm"
        git push origin main
