name: Remove luci-app-tinyfm Folder

on:
  workflow_dispatch: # Allows manual trigger from the GitHub Actions UI

jobs:
  remove-folder:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your repository
    - name: Checkout your repository
      uses: actions/checkout@v3

    # Step 2: Remove the luci-app-tinyfm folder
    - name: Remove luci-app-tinyfm folder
      run: |
        rm -rf luci-app-tinyfm

    # Step 3: Commit and push the deletion
    - name: Commit and push changes
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [ -n "$(git status --porcelain)" ]; then
          git add -A
          git commit -m "Remove luci-app-tinyfm folder"
          git push origin HEAD
        else
          echo "No changes to commit"
        fi
        
